### ISSUE TITLE
Services that make http calls

### ISSUE THREAD

**Issue by victormejia** [daniellmb/angular-test-patterns#6]
Would be great to have a section that shows how to test services that make http calls.

**Comment by lazychino** [comment]
Here are the ngMock examples https://docs.angularjs.org/api/ngMock/service/$httpBackend.
But would be nice to have that here

**Comment by yanivefraim** [comment]
I was thinking of adding a service api call to a mock api and adding a test for it. @daniellmb , what do you think? Can I add a PR here for that?

**Comment by daniellmb** [comment]
@yanivefraim yeah, I think showing how to mock and test an $http call would be a great test pattern to add in the project.

**Comment by yanivefraim** [comment]
@daniellmb Cool, I am already on it. Will take some time - I'm pretty busy, trying to free some time to do this (just did some similar tests with $httpbackend on another project, will use it here)

**Comment by yanivefraim** [comment]
Merged, issue can be closed

**Comment by daniellmb** [comment]
To you @yanivefraim for getting this in!
